# The URL the site will be built for
base_url = "https://neverix.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "tabi"

title = "weblog"
taxonomies = [{name = "tags", feed = true}]

ignored_content = ["*.qmd", "*.ipynb"]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "css"

[extra]
# Put all your custom variables here
allowed_domains = [
    { directive = "font-src", domains = ["'self'", "data:"] },
    { directive = "img-src", domains = ["'self'", "https://*", "data:"] },
    { directive = "script-src", domains = ["'self'"] },
    { directive = "style-src", domains = ["'self'"] },
    { directive = "frame-src", domains = ["'self'"] },
]

skin = "lavender"
override_serif_with_sans = true

menu = [
    { name = "blog", url = "blog", trailing_slash = true },
    { name = "archive", url = "archive", trailing_slash = true },
    { name = "tags", url = "tags", trailing_slash = true },
    { name = "projects", url = "projects", trailing_slash = true },
    { name = "about", url = "about", trailing_slash = true },
]

quick_navigation_buttons = true
bottom_footnotes = true
copy_button = true

katex = true
mermaid = true

socials = [
    { name = "github", url = "https://github.com/neverix/", icon = "github" },
    { name = "twitter", url = "https://x.com/neverrixx/", icon = "twitter" },
    # { name = "soundcloud", url = "https://soundcloud.com/oskerwyld", icon = "soundcloud" },
    # { name = "instagram", url = "https://instagram.com/oskerwyld", icon = "instagram" },
    # { name = "youtube", url = "https://youtube.com/@oskerwyld", icon = "youtube" },
    # { name = "spotify", url = "https://open.spotify.com/artist/5Hv2bYBhMp1lUHFri06xkE", icon = "spotify" },
]

footer_menu = [
    {url = "about", name = "about", trailing_slash = true},
    # {url = "privacy", name = "privacy", trailing_slash = true},
    # {url = "sitemap.xml", name = "sitemap", trailing_slash = false},
    # {url = "https://example.com", name = "external link", trailing_slash = true},
]

[extra.utterances]
enabled_for_all_posts = false
automatic_loading = true
repo = "neverix/weblog"
issue_term = "pathname"
label = "💬"
light_theme = "github-light"
dark_theme = "photon-dark"
lazy_loading = true